api:
  id: "12345678" 

app:
  name:  "pricing-availability" 
  version: "1.0.0"  
  env: "prod"
http:
  host: "0.0.0.0"
  port: "8081"
  
smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "donotreply@ntnusa.com,ntnmule@prowesssoft.com"
wsdl:
  location: "https://ntnpd.opc.oracleoutsourcing.com/PD920/CPQPartsManager?wsdl"
  service: "CPQPartsManagerService"
  port: "CPQPartsManagerPort"
  address: "https://ntnpd.opc.oracleoutsourcing.com:443/PD920/CPQPartsManager"
  userName: "BIZSERVICE"