#%RAML 1.0 SecurityScheme
type: OAuth 2.0
describedBy:
  headers:
    clientId:
      type: string
      example:
        value: "ftweyte746r326e3f6253re"
    clientSecret:
      type: string
      example:
        value: "jqhdid632re62rd62r6"
 